### ISSUE TITLE
Class Diagrams

### ISSUE THREAD

**Issue by logan-nielsen** [logan-nielsen/Frappuccino-Paradise-Group-3#13]
- User Database contains:
  - Customer
    - Barista
      - Manager
- Inventory contains:
  -  Inventory Items
- Menu contains:
  - Menu Item contains:
    - Inventory Items
- Order Database contains:
  - Order contains:
    - Menu Items
    - Add-Ons

**Comment by gtonks** [comment]
Finished and uploaded
